# ClusterIP service for application-level access to any postgres replica
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: middleware
  labels:
    app: postgres
    version: "16"
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
